In [1]:
import warnings
warnings.simplefilter(action='ignore', category=UserWarning)

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import plotly.graph_objs as go
import plotly.express as px
from plotly.subplots import make_subplots
import gzip
from datetime import datetime, timedelta
from statistics import mean
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
import seaborn as sns
import matplotlib.pyplot as plt
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Input, Dense, LeakyReLU, BatchNormalization, ReLU
from tensorflow.keras.activations import sigmoid, tanh
from tensorflow.keras.utils import plot_model

from sklearn.preprocessing import MinMaxScaler

from tqdm import tqdm
import csv
import random

In [2]:
def retrieve_data(varname, filename):
    df = pd.read_csv(filename)
    df["Date"] = pd.to_datetime(df["Date"])
    return df

def create_classification_data(df, lookback):
    rows = []
    columns = ['Date', 'SP500_relative_change_perc_1'] # date and target
    for i in range(1, lookback + 1):
        new_columns = df.columns.tolist()[1:]
        for x in range(len(new_columns)):
            new_columns[x] = new_columns[x] + "_t-" + str(i)
        columns = columns + new_columns
        
    for i, row in enumerate(df.iterrows()):
        if i > lookback:
            new_row = [row[1][0], row[1][2]]
            for x in range(1, lookback + 1):
                add_row = df.iloc[i - x].tolist()
                new_row = new_row + add_row[1:]
            rows.append(new_row)
    df2 = pd.DataFrame(rows)
    df2.columns = columns
    return df2

def create_train_val_test(df, year_val, year_test, perc_train=None):
    if perc_train == None:
        val = df[df['Date'].dt.year == year_val]
        test = df[df['Date'].dt.year == year_test]
        train = df[df['Date'].dt.year != year_val]
        train = train[train['Date'].dt.year != year_test]
    else:
        train = df.head(round(len(df) * perc_train))
        val = df.tail(len(df) - len(train))
        test = val.tail(round(0.5 * len(val)))
        val = df.head(len(val) - len(test))
    
    y_train = train['SP500_relative_change_perc_1']
    x_train = train.drop(['SP500_relative_change_perc_1'], axis=1)
    
    y_val = val['SP500_relative_change_perc_1']
    x_val = val.drop(['SP500_relative_change_perc_1'], axis=1)
    
    y_test = test['SP500_relative_change_perc_1']
    x_test = test.drop(['SP500_relative_change_perc_1'], axis=1)
    
    return x_train, y_train, x_val, y_val, x_test, y_test

def scale_data(x):
    standard_scaler = MinMaxScaler()
    x = x.drop(["Date"], axis=1)
    x_scaled = pd.DataFrame(standard_scaler.fit_transform(x), columns=x.columns)
    return x_scaled

In [3]:
class AE(object):
    def __init__(self, x, activation_functions, batch_sizes, input_size=1500):
        global x_train
        global x_val
        global epochs
        
        print(f"x {x}")
        
        self.x_train = x_train
        self.x_val = x_val
        self.epochs = epochs
        
        self.activation_function = "sigmoid"
        
        self.nodes1 = x[0]
        self.nodes2 = x[1]
        self.nodes3 = x[2]
        
        self.encoding_size = 0.75 * input_size
        
        self.batch_normalization = 1
        self.batch_size = 128
        
    def fit(self):
        input_shape = x_train.shape[1]
        visible = Input(shape=(input_shape,))
        
        # ENCODER
        # encoder layer 1
        encoder = Dense(self.nodes1)(visible)

        # apply batch normalization
        if self.batch_normalization == 1:
            encoder = BatchNormalization()(encoder)

        # activate layer
        if self.activation_function == "LeakyReLU":
            encoder = LeakyReLU()(encoder)
        elif self.activation_function == "ReLU":
            encoder = ReLU()(encoder)
        elif self.activation_function == "sigmoid":
            encoder = sigmoid(encoder)
        elif self.activation_function == "tanh":
            encoder = tanh(encoder)
        
        # encoder layer 2
        if self.nodes2 > 0:
            encoder = Dense(self.nodes2)(encoder)
            
            # apply batch normalization
            if self.batch_normalization == 1:
                encoder = BatchNormalization()(encoder)
            
            # activate layer
            if self.activation_function == "LeakyReLU":
                encoder = LeakyReLU()(encoder)
            elif self.activation_function == "ReLU":
                encoder = ReLU()(encoder)
            elif self.activation_function == "sigmoid":
                encoder = sigmoid(encoder)
            elif self.activation_function == "tanh":
                encoder = tanh(encoder)
        
        # encoder layer 3
        if self.nodes3 > 0:
            encoder = Dense(self.nodes3)(encoder)
            
            # apply batch normalization
            if self.batch_normalization == 1:
                encoder = BatchNormalization()(encoder)
                
            # activate layer
            if self.activation_function == "LeakyReLU":
                encoder = LeakyReLU()(encoder)
            elif self.activation_function == "ReLU":
                encoder = ReLU()(encoder)
            elif self.activation_function == "sigmoid":
                encoder = sigmoid(encoder)
            elif self.activation_function == "tanh":
                encoder = tanh(encoder)
        
        # ENCODING
        encoding = Dense(self.encoding_size)(encoder) 
        
        # DECODER
        # decoder layer 1
        if self.nodes3 > 0:
            decoder = Dense(self.nodes3)(encoding)
            
            # apply batch normalization
            if self.batch_normalization == 1:
                decoder = BatchNormalization()(decoder)
                
            # activate layer
            if self.activation_function == "LeakyReLU":
                decoder = LeakyReLU()(decoder)
            elif self.activation_function == "ReLU":
                decoder = ReLU()(decoder)
            elif self.activation_function == "sigmoid":
                decoder = sigmoid(decoder)
            elif self.activation_function == "tanh":
                decoder = tanh(decoder)
        
        # decoder layer 2
        if self.nodes2 > 0:
            if self.nodes3 == 0:
                decoder = Dense(self.nodes2)(encoding)
            else:
                decoder = Dense(self.nodes2)(decoder)
            
            # apply batch normalization
            if self.batch_normalization == 1:
                decoder = BatchNormalization()(decoder)
                
            # activate layer
            if self.activation_function == "LeakyReLU":
                decoder = LeakyReLU()(decoder)
            elif self.activation_function == "ReLU":
                decoder = ReLU()(decoder)
            elif self.activation_function == "sigmoid":
                decoder = sigmoid(decoder)
            elif self.activation_function == "tanh":
                decoder = tanh(decoder)
        
        # decoder layer 3
        if self.nodes2 == 0 and self.nodes3 == 0:
            decoder = Dense(self.nodes1)(encoding)
        else:
            decoder = Dense(self.nodes1)(decoder)

        # apply batch normalization
        if self.batch_normalization == 1:
            decoder = BatchNormalization()(decoder)

        # activate layer
        if self.activation_function == "LeakyReLU":
            decoder = LeakyReLU()(decoder)
        elif self.activation_function == "ReLU":
            decoder = ReLU()(decoder)
        elif self.activation_function == "sigmoid":
            decoder = sigmoid(decoder)
        elif self.activation_function == "tanh":
            decoder = tanh(decoder)
            
        output = Dense(input_shape, activation='linear')(decoder)
        
        model = Model(inputs=visible, outputs=output)
        model.compile(optimizer='adam', loss='mse')
        
        history = model.fit(self.x_train, self.x_train, 
                    epochs=self.epochs, batch_size=self.batch_size, verbose=0, 
                    validation_data=(self.x_val, self.x_val))
        
        train_loss = history.history['loss'][-1]
        val_loss = history.history['val_loss'][-1]
        return train_loss, val_loss

In [4]:
def calculate_fitness(x, train_loss, val_loss, input_size):
    """
    nodes1 = x[1]
    nodes2 = x[2]
    nodes3 = x[3]

    encoding_size = x[4] # goed als het kleiner is
    
    fitness = val_loss * (nodes1 + 2 * nodes2 + 3 * nodes3) * (encoding_size / input_size)
    """
#     nodes1 = x[1]
#     nodes2 = x[2]
#     nodes3 = x[3]

#     encoding_size = x[4] # goed als het kleiner is
    
#     fitness = (val_loss ** 3) * (nodes1 + 2 * nodes2 + 3 * nodes3) * max(0.1, (encoding_size / input_size))
    fitness = val_loss
    return fitness

In [5]:
class EA(object):
    def __init__(self, population_size, activation_functions, batch_sizes, variables):
        self.population_size = population_size
        self.a = 0.2
        self.activation_functions = activation_functions
        self.batch_sizes = batch_sizes
        self.variables = variables
        
    def evaluate(self, x):
        """
        include in fitness function
            relative difference between train_loss and val_loss (smaller is better)
            number of layers (smaller is better)
            bottleneck size (smaller is better)
            val_loss (smaller is better)
        
        """
        ae = AE(x, activation_functions, batch_sizes)
        train_loss, val_loss = ae.fit()
        fitness = calculate_fitness(x, train_loss, val_loss, self.variables)
        return fitness
    
    def select_triple(self, candidate, population):
        # select three random instances for differential evolution
        x1, x2, x3 = np.random.choice(range(len(population))), np.random.choice(range(len(population))), np.random.choice(range(len(population)))
        while candidate == x1 or candidate == x2 or candidate == x3 or x1 == x2 or x2 == x3 or x1 == x3:
            # keep selecting new ones until candidate != x1 != x2 != x3
            x1, x2, x3 = np.random.choice(range(len(population))), np.random.choice(range(len(population))), np.random.choice(range(len(population)))
        return population[x1], population[x2], population[x3]
    
    def mutate(self, x1, x2, x3):
        mutated = x1 + (self.a * (x3 - x2))
        print(f"mutated {mutated}")
        # nodes layer 1
        mutated[0] = round(mutated[0])
        mutated[0] = max(1, mutated[0]) # must be at least one

        # nodes layer 2
        mutated[1] = round(mutated[1])
        mutated[1] = max(0, mutated[1])

        # nodes layer 3
        mutated[2] = round(mutated[2])
        mutated[2] = max(0, mutated[2])
        return mutated
        
    def recombine(self, candidate, mutation):
        for i in range(candidate.shape[0]):
            prob = np.random.randint(0, 2)
            if prob == 1:
                candidate[i] = mutation[i]
        print(f"candidate {candidate}")
        # nodes 3 can only be non-zero if nodes 2 is non-zero
        if candidate[1] == 0:
            candidate[2] = 0
        # nodes per layer must be at least as large as the encoding size (or 0 for nodes2 and nodes3)
        candidate[1] = max(candidate[1], 0.75 * self.variables)

        if candidate[1] < 0.75 * self.variables:
            if candidate[1] <= 0.5 * 0.75 * self.variables:
                candidate[1] = 0
            else:
                candidate[1] = 0.75 * self.variables
        if candidate[2] < 0.75 * self.variables:
            if candidate[2] <= 0.5 * 0.75 * self.variables:
                candidate[2] = 0
            else:
                candidate[2] = 0.75 * self.variables
        return candidate

    def select(self, x_new, f_new, x_old, f_old):
        x_cat = np.concatenate([x_new, x_old], 0)
        f_cat = np.concatenate([f_new, f_old])
        ind = np.argsort(f_cat)
        x = x_cat[ind]
        f = f_cat[ind]
        return x[:self.population_size], f[:self.population_size]
    
    def step(self, x_old, f_old):
        x = np.copy(x_old)
        f = np.copy(f_old)
        for i in tqdm(range(self.population_size), total=self.population_size):
            # choose candidate
            candidate = x[i]
            # select 3 instances for differential evolution
            x1, x2, x3 = self.select_triple(i, x)
            # mutate 3 instances
            mutated_triple = self.mutate(x1, x2, x3)
            # recombine candidate with mutation
            candidate = self.recombine(candidate, mutated_triple)
            x[i] = candidate
            # evaluate candidate solution
            f_candidate = self.evaluate(candidate)
            f[i] = f_candidate
        # select survivors
        x, f = self.select(x, f, x_old, f_old)
        return x, f

In [6]:
with open('AE output/optimization_output_15_04_2022.csv', mode='w', newline='') as output_file:
    csv_writer = csv.writer(output_file, delimiter=',', quotechar='"')
    row = ['activation_function', 'layer1', 'layer2', 'layer3', 'encoding_size', 
            'batch_normalization', 'batch_size']
#           'train_loss', 'val_loss', 'fitness']
    csv_writer.writerow(row)

In [7]:
def init_population(population_size, activation_functions, batch_sizes, variables):
    # generate initial population
    population = []
    print("Creating initial population...")
    for i in tqdm(range(population_size), total=population_size):
#         activation_function = random.randint(0, len(activation_functions) - 1)
#         encoding_size = random.randint(0.1 * variables, variables)
        encoding_size = 0.75 * variables
        nodes1 = random.randint(encoding_size, 1.5 * variables)
        nodes2 = random.randint(encoding_size, 1.5 * variables)
        nodes3 = random.randint(encoding_size, variables)
#         batch_normalization = random.randint(0,1)
#         batch_size = random.randint(0, len(batch_sizes) - 1)
        population.append(np.asarray([nodes1, nodes2, nodes3], dtype='object'))
#         population.append(np.asarray([activation_function, nodes1, nodes2, nodes3, encoding_size, batch_normalization, batch_size], dtype='object'))
    print("Initial population ready")
    return np.asarray(population)

def evaluate_init_population(ea, x):
    # evaluate initial population
    f = []
    print("Evaluating initial population...")
    for i in tqdm(range(x.shape[0]), total=x.shape[0]):
        instance = x[i]
        f.append(ea.evaluate(instance))
    print("Evaluation initial population completed")
    return np.asarray(f)

def print_best(x, activation_functions, batch_sizes, fitness):
    print(f"\nMost suitable parameters -- Fitness of {fitness}:")
#     print(f"\tActivation function:           \t{activation_functions[x[0]]}")
    print(f"\tNodes layer 1:                 \t{x[0]}")
    print(f"\tNodes layer 2:                 \t{x[1]}")
    print(f"\tNodes layer 3:                 \t{x[2]}")
    print(f"\tSize encoding layer:           \t{0.75 * 1500}")
#     print(f"\tBatch Normalization:           \t{x[5]}")
#     print(f"\tBatch Size:                    \t{batch_sizes[x[6]]}")

def extract_population(population, activation_functions, batch_size):
    with open('AE output/optimization_output_15_04_2022.csv', mode='a', newline='') as output_file:
        csv_writer = csv.writer(output_file, delimiter=',', quotechar='"')
        for instance in population:
            row = []
            activation_function = activation_functions[instance[0]]

            nodes1 = instance[0]
            nodes2 = instance[1]
            nodes3 = instance[2]

#             encoding_size = instance[4]

#             batch_normalization = instance[5]
#             batch_size = batch_sizes[instance[6]]
#             csv_writer.writerow([activation_function, nodes1, nodes2, nodes3, encoding_size, batch_normalization, batch_size])

def plot_convergence(f_best):
    fig1 = make_subplots(rows=1, cols=1, specs=[[{'type':'xy'}]])
    
    x_values = []
    for i in range(len(f_best)):
        x_values.append(i)
    fig1.add_trace(go.Scatter(x=x_values, y=f_best, mode="lines"), row=1, col=1)

    fig1.update_layout(
        title = f'Fitness Over Autoencoder Tuning Generations', 
        xaxis1 = dict(title_text = 'Generation'),
        yaxis1 = dict(title_text = "Validation Loss")
    )
    fig1.write_image("Plots/opt autoencoder.png")
    fig1.show()

def validate_best(x, ea):
    print("\nValidating solution...")
    ea.evaluate(x)
    print("Solution validated")

In [10]:
"""
    instance = [activation function, --> one of list
        nodes layer 1, --> integer, not 0
        nodes layer 2, --> integer, may be 0
        nodes layer 3, --> integer, may be 0
        batch_normalization, --> binary integer
        batch_size --> one of list
        ]
"""

lookback = 5
val_year = 2018
test_year = 2019

files = {
    # varname: filename
    "S&P500": "Dataset v3/SP500_combined_data_20220412.csv",
}
for file in files:
    df = retrieve_data(file, files[file])

df = create_classification_data(df, lookback)

x_train, y_train, x_val, y_val, x_test, y_test = create_train_val_test(df, val_year, test_year)

x_train = scale_data(x_train)
x_val = scale_data(x_val)
x_test = scale_data(x_test)

variables = len(x_train.columns)
print(f"Input size: {variables}")
population_size = 20
generations = 10
epochs = 40

activation_functions = ['ReLU', 'LeakyReLU', 'sigmoid', 'tanh']
batch_sizes = [32, 64, 128, 256]

ea = EA(population_size, activation_functions, batch_sizes, variables)
x = init_population(population_size, activation_functions, batch_sizes, variables)
f = evaluate_init_population(ea, x)

populations = []
populations.append(x)
f_best = [f.min()]

start_time = datetime.now()

print("--> STARTING EVOLUTION")
early_stop = 0
for i in range(generations):
    print(f'Generation: {i}\tBest fitness: {f.min()}')
    x, f = ea.step(x, f)
    print(x)
    populations.append(x)

    if f.min() < f_best[-1]:
        f_best.append(f.min())
        early_stop = 0
    else:
        f_best.append(f_best[-1])
        early_stop += 1
#     extract_population(x, activation_functions, batch_sizes)
    if early_stop == 3:
        print("Early stop triggered at generation {i} after not improving fitness for three generations")
        break
print("--> EVOLUTION FINISHED")

end_time = datetime.now()
evolution_time = end_time - start_time
evolution_time_seconds = evolution_time.total_seconds()
print(f"\nElapsed time in minutes: {evolution_time_seconds/60}")

print(f)
print(f.min())
index_best_parameters = np.where(f == f.min())[0][0]
print(index_best_parameters)
print_best(x[index_best_parameters], activation_functions, batch_sizes, f.min())
validate_best(x[index_best_parameters], ea)
plot_convergence(f_best)

  0%|                                                    | 0/20 [00:00<?, ?it/s]

Input size: 1500
Creating initial population...
Initial population ready
Evaluating initial population...
x [1592 1897 1323]


  5%|██▏                                        | 1/20 [01:57<37:16, 117.73s/it]

x [1989 1850 1240]


 10%|████▎                                      | 2/20 [03:51<34:37, 115.41s/it]

x [1774 2081 1198]


 15%|██████▍                                    | 3/20 [05:40<31:53, 112.54s/it]

x [2114 2240 1316]


 20%|████████▌                                  | 4/20 [07:56<32:25, 121.59s/it]

x [1526 1837 1454]


 25%|██████████▊                                | 5/20 [09:30<27:55, 111.71s/it]

x [2030 1422 1213]


 30%|████████████▉                              | 6/20 [11:07<24:57, 106.94s/it]

x [1479 1543 1478]


 35%|███████████████▍                            | 7/20 [12:30<21:25, 98.91s/it]

x [1751 1862 1408]


 40%|█████████████████▏                         | 8/20 [14:19<20:26, 102.20s/it]

x [1908 1156 1295]


 45%|███████████████████▊                        | 9/20 [15:42<17:39, 96.28s/it]

x [2083 1278 1303]


 50%|█████████████████████▌                     | 10/20 [17:19<16:02, 96.26s/it]

x [1705 2109 1433]


 55%|███████████████████████                   | 11/20 [19:17<15:27, 103.04s/it]

x [2156 1289 1376]


 60%|█████████████████████████▏                | 12/20 [21:06<13:59, 104.99s/it]

x [2155 1465 1459]


 65%|███████████████████████████▎              | 13/20 [22:50<12:11, 104.46s/it]

x [2020 1232 1460]


 70%|█████████████████████████████▍            | 14/20 [24:34<10:25, 104.28s/it]

x [1458 1421 1293]


 75%|████████████████████████████████▎          | 15/20 [25:58<08:12, 98.41s/it]

x [1945 1202 1181]


 80%|██████████████████████████████████▍        | 16/20 [27:27<06:21, 95.45s/it]

x [1755 1199 1225]


 85%|████████████████████████████████████▌      | 17/20 [28:52<04:37, 92.35s/it]

x [1242 1389 1268]


 90%|██████████████████████████████████████▋    | 18/20 [30:07<02:54, 87.06s/it]

x [1493 1432 1240]


 95%|████████████████████████████████████████▊  | 19/20 [31:32<01:26, 86.53s/it]

x [1375 1706 1247]


  0%|                                                    | 0/20 [00:00<?, ?it/s]

Evaluation initial population completed
--> STARTING EVOLUTION
Generation: 0	Best fitness: 0.01799594797194004
mutated [1992.4 1216.8 1435.6]
candidate [1592 1897 1323]
x [1592 1897 1323]


  5%|██▏                                        | 1/20 [02:23<45:29, 143.68s/it]

mutated [2020.6 1363.2 1217.8]
candidate [2021 1363 1240]
x [2021 1363 1240]


 10%|████▎                                      | 2/20 [05:08<46:50, 156.14s/it]

mutated [1809.4 2177.6 1431.6]
candidate [1809 2178 1198]
x [1809 2178 1198]


 15%|██████▍                                    | 3/20 [08:38<51:11, 180.68s/it]

mutated [1674.4 2117.6 1419.0]
candidate [1674 2118 1316]
x [1674 2118 1316]


 20%|████████▌                                  | 4/20 [12:15<52:03, 195.22s/it]

mutated [1587.2 2023.6 1325.8]
candidate [1587 2024 1326]
x [1587 2024 1326]


 25%|██████████▊                                | 5/20 [15:37<49:24, 197.62s/it]

mutated [1934.2 1268.6 1249.8]
candidate [2030 1269 1213]
x [2030 1269 1213]


 30%|████████████▉                              | 6/20 [17:35<39:47, 170.51s/it]

mutated [1732.2 1743.6 1390.8]
candidate [1479 1744 1391]
x [1479 1744 1391]


 35%|███████████████                            | 7/20 [20:03<35:19, 163.00s/it]

mutated [2034.2 1333.6 1232.6]
candidate [2034 1862 1233]
x [2034 1862 1233]


 40%|█████████████████▏                         | 8/20 [24:11<38:01, 190.13s/it]

mutated [2052.4 1169.4 1175.6]
candidate [2052 1156 1295]
x [2052 1156 1295]


 45%|███████████████████▎                       | 9/20 [27:19<34:45, 189.60s/it]

mutated [1683.4 1858.2 1338.0]
candidate [2083 1278 1338]
x [2083 1278 1338]


 50%|█████████████████████                     | 10/20 [30:18<31:01, 186.13s/it]

mutated [1969.0 1378.8 1351.2]
candidate [1705 2109 1433]
x [1705 2109 1433]


 55%|███████████████████████                   | 11/20 [34:21<30:33, 203.68s/it]

mutated [1586.4 1711.4 1385.6]
candidate [2156 1289 1386]
x [2156 1289 1386]


 60%|█████████████████████████▏                | 12/20 [37:53<27:28, 206.00s/it]

mutated [1579.6 1273.6 1266.8]
candidate [2155 1274 1267]
x [2155 1274 1267]


 65%|███████████████████████████▎              | 13/20 [41:37<24:40, 211.53s/it]

mutated [1874.6 2193.8 1220.6]
candidate [1875 2194 1221]
x [1875 2194 1221]


 70%|█████████████████████████████▍            | 14/20 [45:57<22:37, 226.26s/it]

mutated [1532.2 2204.0 1298.0]
candidate [1458 2204 1298]
x [1458 2204 1298]


 75%|███████████████████████████████▌          | 15/20 [49:37<18:41, 224.22s/it]

mutated [2016.6 1475.0 1392.2]
candidate [1945 1475 1181]
x [1945 1475 1181]


 80%|█████████████████████████████████▌        | 16/20 [52:46<14:15, 213.89s/it]

mutated [1854.2 2251.0 1206.4]
candidate [1854 1199 1225]
x [1854 1199 1225]


 85%|███████████████████████████████████▋      | 17/20 [55:15<09:42, 194.30s/it]

mutated [1949.0 1414.2 1256.6]
candidate [1949 1414 1257]
x [1949 1414 1257]


 90%|█████████████████████████████████████▊    | 18/20 [58:01<06:11, 185.82s/it]

mutated [2198.0 1248.8 1403.2]
candidate [1493 1432 1240]
x [1493 1432 1240]


 95%|███████████████████████████████████████▉  | 19/20 [59:28<02:35, 155.97s/it]

mutated [1478.2 2044.0 1311.0]
candidate [1478 1706 1247]
x [1478 1706 1247]


  0%|                                                    | 0/20 [00:00<?, ?it/s]

[[1755 1199 1225]
 [1751 1862 1408]
 [1674 2118 1316]
 [1705 2109 1433]
 [1587 2024 1326]
 [1705 2109 1433]
 [1949 1414 1257]
 [1908 1156 1295]
 [1458 1421 1293]
 [2030 1422 1213]
 [1478 1706 1247]
 [1945 1202 1181]
 [2030 1269 1213]
 [2083 1278 1303]
 [1526 1837 1454]
 [1479 1744 1391]
 [1592 1897 1323]
 [2052 1156 1295]
 [1242 1389 1268]
 [2155 1465 1459]]
Generation: 1	Best fitness: 0.01799594797194004
mutated [1775.6 1970.0 1404.6]
candidate [1755 1199 1405]
x [1755 1199 1405]


  5%|██▏                                        | 1/20 [02:31<47:49, 151.01s/it]

mutated [1289.8 1443.2 1286.0]
candidate [1751 1862 1408]
x [1751 1862 1408]


 10%|████▎                                      | 2/20 [05:42<52:26, 174.78s/it]

mutated [1956.0 974.6 1244.6]
candidate [1674 2118 1245]
x [1674 2118 1245]


 15%|██████▍                                    | 3/20 [08:47<50:52, 179.58s/it]

mutated [1678.4 2064.8 1261.4]
candidate [1678 2109 1433]
x [1678 2109 1433]


 20%|████████▌                                  | 4/20 [12:24<51:51, 194.45s/it]

mutated [2065.0 1518.0 1458.6]
candidate [2065 2024 1326]
x [2065 2024 1326]


 25%|██████████▊                                | 5/20 [16:45<54:35, 218.36s/it]

mutated [1969.4 1255.2 1164.6]
candidate [1969 1255 1433]
x [1969 1255 1433]


 30%|████████████▉                              | 6/20 [19:17<45:38, 195.64s/it]

mutated [1332.2 1495.4 1292.0]
candidate [1949 1414 1292]
x [1949 1414 1292]


 35%|███████████████                            | 7/20 [21:59<40:02, 184.80s/it]

mutated [1756.2 2090.2 1449.2]
candidate [1908 1156 1449]
x [1908 1156 1449]


 40%|█████████████████▏                         | 8/20 [25:06<37:04, 185.36s/it]

mutated [1552.2 1824.0 1314.6]
candidate [1458 1421 1293]
x [1458 1421 1293]


 45%|███████████████████▎                       | 9/20 [27:46<32:31, 177.41s/it]

mutated [1993.0 1328.6 1257.4]
candidate [2030 1329 1257]
x [2030 1329 1257]


 50%|█████████████████████                     | 10/20 [31:07<30:48, 184.81s/it]

mutated [1727.8 1740.0 1401.2]
candidate [1478 1740 1401]
x [1478 1740 1401]


 55%|███████████████████████                   | 11/20 [34:21<28:07, 187.53s/it]

mutated [1750.4 1981.8 1244.0]
candidate [1750 1982 1181]
x [1750 1982 1181]


 60%|█████████████████████████▏                | 12/20 [36:22<22:18, 167.27s/it]

mutated [1738.4 1218.8 1432.6]
candidate [1738 1219 1433]
x [1738 1219 1433]


 65%|███████████████████████████▎              | 13/20 [38:02<17:09, 147.08s/it]

mutated [1597.8 1691.0 1391.4]
candidate [1598 1278 1303]
x [1598 1278 1303]


 70%|█████████████████████████████▍            | 14/20 [39:32<12:59, 129.87s/it]

mutated [1804.6 2006.4 1182.4]
candidate [1805 2006 1182]
x [1805 2006 1182]


 75%|███████████████████████████████▌          | 15/20 [41:40<10:45, 129.18s/it]

mutated [2029.4 1089.8 1455.8]
candidate [2029 1744 1456]
x [2029 1744 1456]


 80%|█████████████████████████████████▌        | 16/20 [43:49<08:36, 129.15s/it]

mutated [1480.6 1868.6 1396.0]
candidate [1592 1897 1323]
x [1592 1897 1323]


 85%|███████████████████████████████████▋      | 17/20 [45:49<06:18, 126.23s/it]

mutated [1613.6 1194.0 1400.2]
candidate [2052 1156 1400]
x [2052 1156 1400]


 90%|█████████████████████████████████████▊    | 18/20 [47:40<04:03, 121.71s/it]

mutated [1734.6 1817.8 1423.6]
candidate [1735 1389 1268]
x [1735 1389 1268]


 95%|███████████████████████████████████████▉  | 19/20 [49:23<01:56, 116.07s/it]

mutated [1675.0 1990.4 1450.4]
candidate [1675 1990 1450]
x [1675 1990 1450]


  0%|                                                    | 0/20 [00:00<?, ?it/s]

[[1592 1897 1323]
 [1755 1199 1225]
 [1751 1862 1408]
 [1751 1862 1408]
 [1674 2118 1316]
 [1705 2109 1433]
 [1587 2024 1326]
 [1908 1156 1449]
 [1949 1414 1292]
 [1705 2109 1433]
 [1949 1414 1257]
 [2030 1329 1257]
 [1908 1156 1295]
 [1458 1421 1293]
 [2030 1422 1213]
 [1478 1706 1247]
 [1945 1202 1181]
 [2030 1269 1213]
 [2083 1278 1303]
 [1526 1837 1454]]
Generation: 2	Best fitness: 0.017656367272138596
mutated [1744.4 1227.8 1207.0]
candidate [1592 1897 1323]
x [1592 1897 1323]


  5%|██▏                                        | 1/20 [01:57<37:10, 117.41s/it]

mutated [1494.2 1689.0 1247.0]
candidate [1494 1689 1225]
x [1494 1689 1225]


 10%|████▎                                      | 2/20 [03:39<32:36, 108.69s/it]

mutated [1631.6 1807.4 1299.8]
candidate [1632 1862 1408]
x [1632 1862 1408]


 15%|██████▍                                    | 3/20 [05:37<31:53, 112.58s/it]

mutated [1394.6 1510.6 1323.2]
candidate [1395 1511 1408]
x [1395 1511 1408]


 20%|████████▌                                  | 4/20 [07:04<27:21, 102.58s/it]

mutated [1837.8 1255.4 1183.4]
candidate [1838 1255 1183]
x [1838 1255 1183]


 25%|███████████                                 | 5/20 [08:34<24:30, 98.03s/it]

mutated [1701.4 2024.2 1310.0]
candidate [1705 2109 1433]
x [1705 2109 1433]


 30%|████████████▉                              | 6/20 [10:40<25:05, 107.53s/it]

mutated [2093.2 1273.8 1207.4]
candidate [1587 2024 1326]
x [1587 2024 1326]


 35%|███████████████                            | 7/20 [12:31<23:31, 108.56s/it]

mutated [1583.8 2027.4 1330.4]
candidate [1584 2027 1330]
x [1584 2027 1330]


 40%|█████████████████▏                         | 8/20 [14:19<21:41, 108.43s/it]

mutated [1529.4 1324.4 1279.8]
candidate [1529 1324 1280]
x [1529 1324 1280]


 45%|███████████████████▊                        | 9/20 [15:38<18:11, 99.27s/it]

mutated [2060.8 1246.2 1288.2]
candidate [2061 2109 1433]
x [2061 2109 1433]


 50%|█████████████████████                     | 10/20 [17:52<18:19, 109.96s/it]

mutated [1352.8 1427.0 1366.4]
candidate [1949 1427 1257]
x [1949 1427 1257]


 55%|███████████████████████                   | 11/20 [19:32<16:03, 107.04s/it]

mutated [2060.0 2134.4 1433.6]
candidate [2060 2134 1257]
x [2060 2134 1257]


 60%|█████████████████████████▏                | 12/20 [21:43<15:14, 114.25s/it]

mutated [2063.4 1427.2 1241.0]
candidate [1908 1427 1295]
x [1908 1427 1295]


 65%|███████████████████████████▎              | 13/20 [23:16<12:34, 107.78s/it]

mutated [2001.4 1326.2 1281.8]
candidate [1458 1421 1282]
x [1458 1421 1282]


 70%|██████████████████████████████             | 14/20 [24:34<09:53, 98.95s/it]

mutated [1539.6 1851.2 1315.2]
candidate [1540 1851 1315]
x [1540 1851 1315]


 75%|████████████████████████████████▎          | 15/20 [26:10<08:10, 98.10s/it]

mutated [1570.0 2010.6 1319.6]
candidate [1570 1706 1320]
x [1570 1706 1320]


 80%|██████████████████████████████████▍        | 16/20 [27:47<06:30, 97.74s/it]

mutated [1924.6 1458.6 1273.4]
candidate [1925 1202 1181]
x [1925 1202 1181]


 85%|████████████████████████████████████▌      | 17/20 [29:17<04:45, 95.31s/it]

mutated [1501.8 1570.4 1368.6]
candidate [1502 1269 1213]
x [1502 1269 1213]


 90%|██████████████████████████████████████▋    | 18/20 [30:31<02:57, 88.76s/it]

mutated [1511.0 1236.6 1229.4]
candidate [2083 1237 1229]
x [2083 1237 1229]


 95%|████████████████████████████████████████▊  | 19/20 [32:01<01:29, 89.22s/it]

mutated [2057.2 2069.8 1255.0]
candidate [2057 1837 1454]
x [2057 1837 1454]


  0%|                                                    | 0/20 [00:00<?, ?it/s]

[[1592 1897 1323]
 [1838 1255 1183]
 [2061 2109 1433]
 [1755 1199 1225]
 [1494 1689 1225]
 [2060 2134 1257]
 [1751 1862 1408]
 [1751 1862 1408]
 [1674 2118 1316]
 [1908 1427 1295]
 [1705 2109 1433]
 [1587 2024 1326]
 [1908 1156 1449]
 [1949 1414 1292]
 [1395 1511 1408]
 [1705 2109 1433]
 [1949 1414 1257]
 [2030 1329 1257]
 [1908 1156 1295]
 [1458 1421 1293]]
Generation: 3	Best fitness: 0.017656367272138596
mutated [1724.8 1166.0 1176.6]
candidate [1725 1166 1177]
x [1725 1166 1177]


  5%|██▏                                         | 1/20 [01:14<23:44, 74.97s/it]

mutated [2011.2 2273.0 1285.2]
candidate [2011 1255 1285]
x [2011 1255 1285]


 10%|████▍                                       | 2/20 [02:47<25:40, 85.56s/it]

mutated [1846.0 1144.0 1238.4]
candidate [2061 1144 1433]
x [2061 1144 1433]


 15%|██████▌                                     | 3/20 [04:15<24:27, 86.34s/it]

mutated [1988.8 1111.0 1292.0]
candidate [1989 1199 1225]
x [1989 1199 1225]


 20%|████████▊                                   | 4/20 [05:46<23:29, 88.12s/it]

mutated [1743.4 2211.6 1416.6]
candidate [1743 2212 1225]
x [1743 2212 1225]


 25%|███████████                                 | 5/20 [07:42<24:35, 98.39s/it]

mutated [1662.4 2001.0 1421.8]
candidate [2060 2001 1257]
x [2060 2001 1257]


 30%|████████████▉                              | 6/20 [09:42<24:39, 105.69s/it]

mutated [1672.4 2188.0 1279.4]
candidate [1672 1862 1279]
x [1672 1862 1279]


 35%|███████████████                            | 7/20 [11:24<22:37, 104.46s/it]

mutated [2096.6 1999.0 1311.4]
candidate [1751 1999 1408]
x [1751 1999 1408]


 40%|█████████████████▏                         | 8/20 [13:20<21:38, 108.24s/it]

mutated [1774.8 1229.4 1444.0]
candidate [1775 1229 1316]
x [1775 1229 1316]


 45%|███████████████████▎                       | 9/20 [14:48<18:38, 101.67s/it]

mutated [1904.2 1141.2 1454.6]
candidate [1904 1427 1455]
x [1904 1427 1455]


 50%|█████████████████████▌                     | 10/20 [16:23<16:38, 99.87s/it]

mutated [1927.6 1448.4 1326.0]
candidate [1928 1448 1433]
x [1928 1448 1433]


 55%|███████████████████████▋                   | 11/20 [18:01<14:53, 99.29s/it]

mutated [2087.0 1483.4 1245.2]
candidate [2087 1483 1326]
x [2087 1483 1326]


 60%|█████████████████████████▏                | 12/20 [19:50<13:37, 102.14s/it]

mutated [1934.0 1582.4 1433.0]
candidate [1908 1156 1433]
x [1908 1156 1433]


 65%|███████████████████████████▉               | 13/20 [21:17<11:23, 97.65s/it]

mutated [1947.8 1358.6 1218.6]
candidate [1948 1359 1292]
x [1948 1359 1292]


 70%|██████████████████████████████             | 14/20 [22:56<09:47, 97.98s/it]

mutated [1954.2 1437.0 1326.6]
candidate [1395 1437 1408]
x [1395 1437 1408]


 75%|████████████████████████████████▎          | 15/20 [24:16<07:43, 92.69s/it]

mutated [1989.8 1031.6 1433.0]
candidate [1990 2109 1433]
x [1990 2109 1433]


 80%|█████████████████████████████████▌        | 16/20 [26:27<06:56, 104.10s/it]

mutated [1902.8 1467.6 1472.6]
candidate [1949 1468 1473]
x [1949 1468 1473]


 85%|███████████████████████████████████▋      | 17/20 [28:05<05:06, 102.28s/it]

mutated [1904.0 1173.8 1323.2]
candidate [2030 1329 1323]
x [2030 1329 1323]


 90%|█████████████████████████████████████▊    | 18/20 [29:52<03:27, 103.67s/it]

mutated [1759.0 1843.0 1386.0]
candidate [1908 1156 1295]
x [1908 1156 1295]


 95%|███████████████████████████████████████▉  | 19/20 [31:27<01:41, 101.14s/it]

mutated [1352.0 1261.0 1384.6]
candidate [1352 1261 1385]
x [1352 1261 1385]


  0%|                                                    | 0/20 [00:00<?, ?it/s]

[[1592 1897 1323]
 [2030 1329 1323]
 [2087 1483 1326]
 [1838 1255 1183]
 [1743 2212 1225]
 [2061 2109 1433]
 [1755 1199 1225]
 [1494 1689 1225]
 [2060 2134 1257]
 [1751 1862 1408]
 [1751 1862 1408]
 [1674 2118 1316]
 [1908 1156 1433]
 [1908 1427 1295]
 [1705 2109 1433]
 [1587 2024 1326]
 [1352 1261 1385]
 [1908 1156 1449]
 [1949 1414 1292]
 [1395 1511 1408]]
Generation: 4	Best fitness: 0.017656367272138596
mutated [2070.6 1192.6 1295.4]
candidate [2071 1193 1295]
x [2071 1193 1295]


  5%|██▏                                         | 1/20 [01:34<29:50, 94.21s/it]

mutated [1763.6 1249.0 1229.6]
candidate [2030 1249 1230]
x [2030 1249 1230]


 10%|████▍                                       | 2/20 [03:09<28:31, 95.08s/it]

mutated [1655.2 2004.4 1433.0]
candidate [2087 2004 1433]
x [2087 2004 1433]


 15%|██████▍                                    | 3/20 [05:16<30:59, 109.37s/it]

mutated [1877.8 1343.8 1292.0]
candidate [1878 1255 1292]
x [1878 1255 1292]


 20%|████████▌                                  | 4/20 [06:42<26:42, 100.16s/it]

mutated [1547.4 2113.6 1349.2]
candidate [1547 2212 1225]
x [1547 2212 1225]


 25%|██████████▊                                | 5/20 [08:38<26:27, 105.84s/it]

mutated [1988.4 996.4 1446.4]
candidate [1988 2109 1446]
x [1988 2109 1446]


 30%|████████████▉                              | 6/20 [10:49<26:44, 114.63s/it]

mutated [1593.8 2130.0 1420.2]
candidate [1594 2130 1225]
x [1594 2130 1225]


 35%|███████████████                            | 7/20 [12:39<24:28, 112.95s/it]

mutated [1319.2 1293.4 1368.6]
candidate [1494 1689 1225]
x [1494 1689 1225]


 40%|█████████████████▏                         | 8/20 [14:07<21:00, 105.01s/it]

mutated [1773.2 1458.8 1278.0]
candidate [2060 1459 1278]
x [2060 1459 1278]


 45%|███████████████████▎                       | 9/20 [15:54<19:21, 105.62s/it]

mutated [1997.4 2092.6 1446.0]
candidate [1997 1862 1446]
x [1997 1862 1446]


 50%|█████████████████████                     | 10/20 [17:54<18:19, 109.95s/it]

mutated [1550.8 1514.0 1238.4]
candidate [1551 1514 1238]
x [1551 1514 1238]


 55%|███████████████████████                   | 11/20 [19:18<15:19, 102.18s/it]

mutated [2141.2 1228.0 1242.8]
candidate [2141 2118 1316]
x [2141 2118 1316]


 60%|█████████████████████████▏                | 12/20 [21:31<14:52, 111.61s/it]

mutated [1924.8 1522.6 1300.6]
candidate [1908 1523 1301]
x [1908 1523 1301]


 65%|███████████████████████████▎              | 13/20 [23:08<12:30, 107.22s/it]

mutated [1846.0 1403.4 1296.0]
candidate [1908 1403 1296]
x [1908 1403 1296]


 70%|█████████████████████████████▍            | 14/20 [24:40<10:14, 102.38s/it]

mutated [1637.8 1675.4 1207.0]
candidate [1705 1675 1433]
x [1705 1675 1433]


 75%|███████████████████████████████▌          | 15/20 [26:21<08:30, 102.08s/it]

mutated [2011.2 1893.8 1446.0]
candidate [2011 2024 1446]
x [2011 2024 1446]


 80%|█████████████████████████████████▌        | 16/20 [28:25<07:14, 108.55s/it]

mutated [1578.0 1727.4 1468.6]
candidate [1352 1261 1469]
x [1352 1261 1469]


 85%|████████████████████████████████████▌      | 17/20 [29:40<04:56, 98.70s/it]

mutated [1485.0 1250.6 1443.0]
candidate [1908 1251 1449]
x [1908 1251 1449]


 90%|██████████████████████████████████████▋    | 18/20 [31:10<03:12, 96.01s/it]

mutated [2083.8 2056.0 1444.4]
candidate [2084 1414 1444]
x [2084 1414 1444]


 95%|████████████████████████████████████████▊  | 19/20 [32:52<01:37, 97.65s/it]

mutated [1980.6 1347.0 1399.8]
candidate [1395 1511 1400]
x [1395 1511 1400]


100%|██████████████████████████████████████████| 20/20 [34:17<00:00, 102.87s/it]


[[1592 1897 1323]
 [1594 2130 1225]
 [2030 1329 1323]
 [2087 1483 1326]
 [1395 1511 1400]
 [1838 1255 1183]
 [1743 2212 1225]
 [2061 2109 1433]
 [1755 1199 1225]
 [1494 1689 1225]
 [2060 2134 1257]
 [1751 1862 1408]
 [1878 1255 1292]
 [2011 2024 1446]
 [1751 1862 1408]
 [1674 2118 1316]
 [1908 1156 1433]
 [1908 1427 1295]
 [1705 2109 1433]
 [1587 2024 1326]]
Early stop triggered at generation {i} after not improving fitness for three generations
--> EVOLUTION FINISHED

Elapsed time in minutes: 214.78683703333334
[0.01765637 0.01766631 0.01770606 0.01780161 0.01790145 0.01791849
 0.01794587 0.01799139 0.01799595 0.01801387 0.01803054 0.01803556
 0.01807796 0.0180909  0.01814017 0.0181577  0.0182121  0.01821678
 0.01821902 0.0182209 ]
0.017656367272138596
0

Most suitable parameters -- Fitness of 0.017656367272138596:
	Nodes layer 1:                 	1592
	Nodes layer 2:                 	1897
	Nodes layer 3:                 	1323
	Size encoding layer:           	1125.0

Validating soluti